In [4]:
import numpy as np
A = np.array([[56,0,4.4,68],
              [1.2,104,52,8],
              [1.8,135,99,0.9]])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [5]:
cal = A.sum(axis=0)
print(cal)

[ 59.  239.  155.4  76.9]


In [6]:
yh = 0.9
y = 1
answer = -(y*np.log(yh)+(1-y)*np.log(1-yh))
print(answer)

0.10536051565782628


In [7]:
x=np.array([[[1],[2]],[[3],[4]]])
print(x.shape)

(2, 2, 1)


In [11]:
a = np.random.randn(3,3)
print( a.shape)
b = np.random.randn(2,1)
print(b.shape)
c = a+b

(3, 3)
(2, 1)


ValueError: operands could not be broadcast together with shapes (3,3) (2,1) 

In [12]:
a = np.random.randn(4,3)
print(a.shape)
b = np.random.randn(3,2)
print(b.shape)
c = a*b

(4, 3)
(3, 2)


ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [21]:
a = np.array([[2,1],[1,3]])
print(a)
print(a.shape)
print(np.dot(a,a))

[[2 1]
 [1 3]]
(2, 2)
[[ 5  5]
 [ 5 10]]


In [22]:
a = np.random.randn(3,3)
b = np.random.randn(3,1)
c = a*b
print(c.shape)

(3, 3)


In [23]:
a = 100
b = 200
C = 300
r = (a+b)*(a-b) 
s = (b+c)*(b-c)
j = r+s
print(j)

[[9998.63173873 9996.49617972 9999.87074813]
 [9999.99483728 9999.99887235 9999.99643789]
 [9996.69393473 9999.74230172 9996.94531365]]


r = (a+b)*(a-b) = a*(a-b) + b*(a-b) = a^2 - a*b + a*b - b^2 = a^2 - a^2*b^2  -b^2 * c^2 - c^2
s = (b+c)*(b-c) = b*(b-c) + c*(b-c) = b^2 - b*c + b*c - c^2 = b^2 -b^2 * c^2 - c^2
j = (a+b)*(a-b) + (b+c)*(b-c) 

J = (a+b) * (a-b) + (b+c) * (b-c) = 

In [ ]:
x = np.exp?